# Generated by Django 4.1.4 on 2023-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_date_added_lead_description_lead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
